### ISSUE TITLE
Other Perl spreadsheet module

### ISSUE THREAD

**Issue by nkh** [jimav/Spreadsheet-Edit#1]
Hi, Spreadsheet::Perl author here

https://metacpan.org/pod/Spreadsheet::Perl or https://github.com/nkh/P5-Spreadsheet-Perl

The module is from 2004 so there may be some bit rot.

Have a look at that module there may be ideas, code to re-use, ... in it. Or there may be things that make no sense or could be done better and I'd appreciate the feedback.

If you believe there's commonality, I'd be happy to cooperate on something.

I haven't had tome to look at your module in detail yet but I hope I'll have some time this week.

Keep the good work.

**Comment by jimav** [comment]
Heh.  More than a year later and I have not replied substantively.   I think it's safe to say that neither of us has the bandwidth to try integrating in some way.  And anyway, I think we were aiming at somewhat different goals.   I do wish Spreadsheet::Edit had support for formats on a cell-by-cell basis.   But alas.

Currently Spreadsheet::Edit only allows specifying per-column formats for when importing .csv to spreadsheets, and auto-detects when 'text' (not numeric) is needed to avoid corruption in many common cases.

I'm going to close this to get it off the issues list.  Please open a new ticket if you decide we should think about this again.
Best wishes!
-Jim
